name: my_mushrooms_hunter 
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2

  firebase_ui_auth: ^1.12.1
  firebase_ui_oauth_google: ^1.2.16
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.5.3 
  geolocator: ^10.1.0
  image_picker: ^1.0.7 
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  intl: ^0.18.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/

