// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY2dCezEUnLa8p3EFb6aY7yc-RT86e0vE',
    appId: '1:941895250603:web:cf696acd05d1cf115a7dee',
    messagingSenderId: '941895250603',
    projectId: 'my-mushrooms-hunter',
    authDomain: 'my-mushrooms-hunter.firebaseapp.com',
    storageBucket: 'my-mushrooms-hunter.appspot.com',
    measurementId: 'G-YWJTDT3CQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtbtuoJz6iPNWQJ8lBu2m7LsMrcZvSO64',
    appId: '1:941895250603:android:9d1be4e7e42ab3af5a7dee',
    messagingSenderId: '941895250603',
    projectId: 'my-mushrooms-hunter',
    storageBucket: 'my-mushrooms-hunter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXT_J9XYa61tDPJen8fy_Y38rzUhGhmKw',
    appId: '1:941895250603:ios:1c463ccfa45930245a7dee',
    messagingSenderId: '941895250603',
    projectId: 'my-mushrooms-hunter',
    storageBucket: 'my-mushrooms-hunter.appspot.com',
    iosBundleId: 'com.annacar.mymushroomshunter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXT_J9XYa61tDPJen8fy_Y38rzUhGhmKw',
    appId: '1:941895250603:ios:5a9a3073aa2a774d5a7dee',
    messagingSenderId: '941895250603',
    projectId: 'my-mushrooms-hunter',
    storageBucket: 'my-mushrooms-hunter.appspot.com',
    iosBundleId: 'com.annacar.mymushroomshunter.RunnerTests',
  );
}
